#ifndef OPERATION_H
#define OPERATION_H

enum Operation {
    INIT,
    OPEN_FILE,
    LOAD_DATA,
    SCALE_MINUS,
    SCALE_PLUS,
    UP_MOVEMENT,
    DOWN_MOVEMENT,
    LEFT_MOVEMENT,
    RIGHT_MOVEMENT,
    BACK_MOVEMENT,
    FORWARD_MOVEMENT,
    XCW_ROTATION,
    XCCW_ROTATION,
    YCW_ROTATION,
    YCCW_ROTATION,
    ZCW_ROTATION,
    ZCCW_ROTATION,
    NORMALIZE_SHAPE,
};

#endif // OPERATION_H
