#ifndef ERROR_H
#define ERROR_H

enum Error {
    NO_ERROR,
    OPEN_FILE_ERROR,
    PARSE_CSV_ERROR,
    INVALID_COLUMN_ERROR,
    INVALID_FIELD_ERROR,
    REGION_NOT_EXIST,
    SKIP_RECORD_ERROR,
};

#endif // ERROR_H
